"""
universe.py — Σταθερό universe μετοχών (ticker -> όνομα/κλάδος/ήπειρος) που
χρησιμοποιεί το aggregate.py για ticker-matching στα άρθρα ειδήσεων.

Seed data παρμένο/προσαρμοσμένο από το ~/trading-copilot/scanner/scan.py
(TICKERS + MARKET_META) — ίδιο universe concept, μικρότερο υποσύνολο εδώ
γιατί ο στόχος του market-intel δεν είναι πλήρες screening αλλά news-driven
ranking πάνω σε τα πιο likely-to-be-in-the-news ονόματα ανά κλάδο.

Το προαιρετικό κλειδί "match" ορίζει τη λέξη που ψάχνει το aggregate.py στον
τίτλο/περίληψη άρθρου (αντί για την προεπιλογή: την πρώτη λέξη του "name").
Χρησιμοποιείται όταν η πρώτη λέξη είναι πολύ γενική (π.χ. "General", "American",
"Home") και θα έδινε false positives.
"""

# continent: "na" (Βόρεια Αμερική), "eu" (Ευρώπη), "as" (Ασία), "oc" (Ωκεανία)
UNIVERSE = {
    # --- Τεχνολογία / Ημιαγωγοί (Βόρεια Αμερική) ---
    "NVDA": {"name": "NVIDIA", "sector": "Τεχνολογία", "continent": "na"},
    "AAPL": {"name": "Apple", "sector": "Τεχνολογία", "continent": "na"},
    "MSFT": {"name": "Microsoft", "sector": "Τεχνολογία", "continent": "na"},
    "GOOGL": {"name": "Alphabet", "sector": "Τεχνολογία", "continent": "na"},
    "AMZN": {"name": "Amazon", "sector": "Τεχνολογία", "continent": "na"},
    "META": {"name": "Meta Platforms", "sector": "Τεχνολογία", "continent": "na", "match": "Meta"},
    "AVGO": {"name": "Broadcom", "sector": "Ημιαγωγοί", "continent": "na"},
    "AMD": {"name": "Advanced Micro Devices", "sector": "Ημιαγωγοί", "continent": "na", "match": "AMD"},
    "ORCL": {"name": "Oracle", "sector": "Τεχνολογία", "continent": "na"},
    "CRM": {"name": "Salesforce", "sector": "Τεχνολογία", "continent": "na"},
    "ADBE": {"name": "Adobe", "sector": "Τεχνολογία", "continent": "na"},
    "PLTR": {"name": "Palantir Technologies", "sector": "Τεχνολογία", "continent": "na", "match": "Palantir"},
    "CSCO": {"name": "Cisco Systems", "sector": "Τεχνολογία", "continent": "na", "match": "Cisco"},
    "INTC": {"name": "Intel", "sector": "Ημιαγωγοί", "continent": "na"},
    "QCOM": {"name": "Qualcomm", "sector": "Ημιαγωγοί", "continent": "na"},
    "IBM": {"name": "IBM", "sector": "Τεχνολογία", "continent": "na"},
    "NOW": {"name": "ServiceNow", "sector": "Τεχνολογία", "continent": "na", "match": "ServiceNow"},
    "PANW": {"name": "Palo Alto Networks", "sector": "Κυβερνοασφάλεια", "continent": "na", "match": "Palo Alto"},
    "CRWD": {"name": "CrowdStrike", "sector": "Κυβερνοασφάλεια", "continent": "na", "match": "CrowdStrike"},
    "ANET": {"name": "Arista Networks", "sector": "Τεχνολογία", "continent": "na", "match": "Arista"},
    "MU": {"name": "Micron Technology", "sector": "Ημιαγωγοί", "continent": "na", "match": "Micron"},
    "LRCX": {"name": "Lam Research", "sector": "Ημιαγωγοί", "continent": "na", "match": "Lam Research"},
    "AMAT": {"name": "Applied Materials", "sector": "Ημιαγωγοί", "continent": "na", "match": "Applied Materials"},
    "TXN": {"name": "Texas Instruments", "sector": "Ημιαγωγοί", "continent": "na", "match": "Texas Instruments"},
    "KLAC": {"name": "KLA Corporation", "sector": "Ημιαγωγοί", "continent": "na", "match": "KLA"},
    "SHOP": {"name": "Shopify", "sector": "Τεχνολογία", "continent": "na", "match": "Shopify"},
    "SNOW": {"name": "Snowflake", "sector": "Τεχνολογία", "continent": "na", "match": "Snowflake"},
    "SPOT": {"name": "Spotify", "sector": "Μέσα Ενημέρωσης", "continent": "na", "match": "Spotify"},
    "ABNB": {"name": "Airbnb", "sector": "Τουρισμός", "continent": "na", "match": "Airbnb"},
    # --- Αυτοκίνητο / Βιομηχανία / Άμυνα ---
    "TSLA": {"name": "Tesla", "sector": "Αυτοκίνητο", "continent": "na"},
    "GE": {"name": "GE Aerospace", "sector": "Αεροδιαστημική", "continent": "na", "match": "GE Aerospace"},
    "CAT": {"name": "Caterpillar", "sector": "Βιομηχανία", "continent": "na"},
    "RTX": {"name": "RTX Corporation", "sector": "Άμυνα", "continent": "na", "match": "RTX"},
    "BA": {"name": "Boeing", "sector": "Αεροδιαστημική", "continent": "na"},
    "LMT": {"name": "Lockheed Martin", "sector": "Άμυνα", "continent": "na", "match": "Lockheed"},
    "DE": {"name": "Deere & Company", "sector": "Βιομηχανία", "continent": "na", "match": "Deere"},
    "HON": {"name": "Honeywell", "sector": "Βιομηχανία", "continent": "na"},
    "F": {"name": "Ford Motor", "sector": "Αυτοκίνητο", "continent": "na", "match": "Ford"},
    "GM": {"name": "General Motors", "sector": "Αυτοκίνητο", "continent": "na", "match": "General Motors"},
    "RIVN": {"name": "Rivian Automotive", "sector": "Αυτοκίνητο", "continent": "na", "match": "Rivian"},
    # --- Χρηματοοικονομικά ---
    "JPM": {"name": "JPMorgan Chase", "sector": "Τράπεζες", "continent": "na", "match": "JPMorgan"},
    "BAC": {"name": "Bank of America", "sector": "Τράπεζες", "continent": "na", "match": "Bank of America"},
    "GS": {"name": "Goldman Sachs", "sector": "Τράπεζες", "continent": "na", "match": "Goldman Sachs"},
    "MS": {"name": "Morgan Stanley", "sector": "Τράπεζες", "continent": "na", "match": "Morgan Stanley"},
    "WFC": {"name": "Wells Fargo", "sector": "Τράπεζες", "continent": "na", "match": "Wells Fargo"},
    "C": {"name": "Citigroup", "sector": "Τράπεζες", "continent": "na", "match": "Citigroup"},
    "V": {"name": "Visa", "sector": "Πληρωμές", "continent": "na"},
    "MA": {"name": "Mastercard", "sector": "Πληρωμές", "continent": "na"},
    "PYPL": {"name": "PayPal", "sector": "Πληρωμές", "continent": "na"},
    "AXP": {"name": "American Express", "sector": "Πληρωμές", "continent": "na", "match": "American Express"},
    "BLK": {"name": "BlackRock", "sector": "Χρηματοοικονομικά", "continent": "na"},
    "SCHW": {"name": "Charles Schwab", "sector": "Χρηματοοικονομικά", "continent": "na", "match": "Schwab"},
    # --- Ενέργεια ---
    "XOM": {"name": "ExxonMobil", "sector": "Ενέργεια", "continent": "na"},
    "CVX": {"name": "Chevron", "sector": "Ενέργεια", "continent": "na"},
    "COP": {"name": "ConocoPhillips", "sector": "Ενέργεια", "continent": "na"},
    "NEE": {"name": "NextEra Energy", "sector": "Ενεργειακές Υπηρεσίες", "continent": "na", "match": "NextEra"},
    # --- Υγεία ---
    "LLY": {"name": "Eli Lilly", "sector": "Υγεία", "continent": "na", "match": "Eli Lilly"},
    "JNJ": {"name": "Johnson & Johnson", "sector": "Υγεία", "continent": "na", "match": "Johnson & Johnson"},
    "UNH": {"name": "UnitedHealth Group", "sector": "Υγεία", "continent": "na", "match": "UnitedHealth"},
    "ABBV": {"name": "AbbVie", "sector": "Υγεία", "continent": "na"},
    "MRK": {"name": "Merck & Co.", "sector": "Υγεία", "continent": "na", "match": "Merck"},
    "PFE": {"name": "Pfizer", "sector": "Υγεία", "continent": "na"},
    "VRTX": {"name": "Vertex Pharmaceuticals", "sector": "Υγεία", "continent": "na", "match": "Vertex Pharmaceuticals"},
    "ISRG": {"name": "Intuitive Surgical", "sector": "Υγεία", "continent": "na", "match": "Intuitive Surgical"},
    "NVO": {"name": "Novo Nordisk", "sector": "Υγεία", "continent": "na", "match": "Novo Nordisk"},
    "MRNA": {"name": "Moderna", "sector": "Υγεία", "continent": "na", "match": "Moderna"},
    # --- Καταναλωτικά / Λιανεμπόριο / Μέσα ---
    "WMT": {"name": "Walmart", "sector": "Λιανεμπόριο", "continent": "na"},
    "COST": {"name": "Costco Wholesale", "sector": "Λιανεμπόριο", "continent": "na", "match": "Costco"},
    "HD": {"name": "Home Depot", "sector": "Λιανεμπόριο", "continent": "na", "match": "Home Depot"},
    "LOW": {"name": "Lowe's", "sector": "Λιανεμπόριο", "continent": "na", "match": "Lowe's"},
    "TGT": {"name": "Target", "sector": "Λιανεμπόριο", "continent": "na", "match": "Target Corp"},
    "NKE": {"name": "Nike", "sector": "Καταναλωτικά", "continent": "na"},
    "SBUX": {"name": "Starbucks", "sector": "Καταναλωτικά", "continent": "na"},
    "MCD": {"name": "McDonald's", "sector": "Καταναλωτικά", "continent": "na", "match": "McDonald's"},
    "KO": {"name": "Coca-Cola", "sector": "Καταναλωτικά", "continent": "na", "match": "Coca-Cola"},
    "PEP": {"name": "PepsiCo", "sector": "Καταναλωτικά", "continent": "na"},
    "PG": {"name": "Procter & Gamble", "sector": "Καταναλωτικά", "continent": "na", "match": "Procter & Gamble"},
    "DIS": {"name": "Walt Disney", "sector": "Μέσα Ενημέρωσης", "continent": "na", "match": "Disney"},
    "NFLX": {"name": "Netflix", "sector": "Μέσα Ενημέρωσης", "continent": "na"},
    "CMCSA": {"name": "Comcast", "sector": "Μέσα Ενημέρωσης", "continent": "na"},
    "UBER": {"name": "Uber Technologies", "sector": "Μεταφορές", "continent": "na", "match": "Uber"},
    # --- Ευρώπη ---
    "SAP": {"name": "SAP", "sector": "Τεχνολογία", "continent": "eu"},
    "ASML": {"name": "ASML Holding", "sector": "Ημιαγωγοί", "continent": "eu", "match": "ASML"},
    "MC.PA": {"name": "LVMH", "sector": "Πολυτέλεια", "continent": "eu", "match": "LVMH"},
    "OR.PA": {"name": "L'Oréal", "sector": "Καταναλωτικά", "continent": "eu", "match": "L'Oréal"},
    "NESN": {"name": "Nestlé", "sector": "Καταναλωτικά", "continent": "eu", "match": "Nestlé"},
    "SHEL": {"name": "Shell", "sector": "Ενέργεια", "continent": "eu"},
    "BP": {"name": "BP", "sector": "Ενέργεια", "continent": "eu"},
    "TTE": {"name": "TotalEnergies", "sector": "Ενέργεια", "continent": "eu", "match": "TotalEnergies"},
    "AZN": {"name": "AstraZeneca", "sector": "Υγεία", "continent": "eu", "match": "AstraZeneca"},
    "NOVN": {"name": "Novartis", "sector": "Υγεία", "continent": "eu", "match": "Novartis"},
    "ROG": {"name": "Roche Holding", "sector": "Υγεία", "continent": "eu", "match": "Roche"},
    "SIE": {"name": "Siemens", "sector": "Βιομηχανία", "continent": "eu"},
    "AIR.PA": {"name": "Airbus", "sector": "Αεροδιαστημική", "continent": "eu", "match": "Airbus"},
    "HSBA": {"name": "HSBC", "sector": "Τράπεζες", "continent": "eu"},
    "DBK": {"name": "Deutsche Bank", "sector": "Τράπεζες", "continent": "eu", "match": "Deutsche Bank"},
    "UL": {"name": "Unilever", "sector": "Καταναλωτικά", "continent": "eu", "match": "Unilever"},
    "VOW3": {"name": "Volkswagen", "sector": "Αυτοκίνητο", "continent": "eu", "match": "Volkswagen"},
    "MBG": {"name": "Mercedes-Benz Group", "sector": "Αυτοκίνητο", "continent": "eu", "match": "Mercedes-Benz"},
    "IBE": {"name": "Iberdrola", "sector": "Ενεργειακές Υπηρεσίες", "continent": "eu", "match": "Iberdrola"},
    "INGA": {"name": "ING Group", "sector": "Τράπεζες", "continent": "eu", "match": "ING Group"},
    # --- Ασία ---
    "TSM": {"name": "Taiwan Semiconductor", "sector": "Ημιαγωγοί", "continent": "as", "match": "Taiwan Semiconductor"},
    "BABA": {"name": "Alibaba Group", "sector": "Τεχνολογία", "continent": "as", "match": "Alibaba"},
    "TCEHY": {"name": "Tencent Holdings", "sector": "Τεχνολογία", "continent": "as", "match": "Tencent"},
    "JD": {"name": "JD.com", "sector": "Τεχνολογία", "continent": "as", "match": "JD.com"},
    "PDD": {"name": "PDD Holdings", "sector": "Τεχνολογία", "continent": "as", "match": "PDD Holdings"},
    "SONY": {"name": "Sony Group", "sector": "Τεχνολογία", "continent": "as", "match": "Sony"},
    "TM": {"name": "Toyota Motor", "sector": "Αυτοκίνητο", "continent": "as", "match": "Toyota"},
    "HMC": {"name": "Honda Motor", "sector": "Αυτοκίνητο", "continent": "as", "match": "Honda"},
    "005930.KS": {"name": "Samsung Electronics", "sector": "Τεχνολογία", "continent": "as", "match": "Samsung"},
    "005380.KS": {"name": "Hyundai Motor", "sector": "Αυτοκίνητο", "continent": "as", "match": "Hyundai"},
    "9988.HK": {"name": "Alibaba Group (HK)", "sector": "Τεχνολογία", "continent": "as", "match": "Alibaba"},
    "9999.HK": {"name": "NetEase", "sector": "Τεχνολογία", "continent": "as", "match": "NetEase"},
    "INFY": {"name": "Infosys", "sector": "Τεχνολογία", "continent": "as", "match": "Infosys"},
    "TCS.NS": {"name": "Tata Consultancy Services", "sector": "Τεχνολογία", "continent": "as", "match": "Tata Consultancy"},
    "RELIANCE.NS": {"name": "Reliance Industries", "sector": "Ενέργεια", "continent": "as", "match": "Reliance Industries"},
    # --- Ωκεανία ---
    "BHP": {"name": "BHP Group", "sector": "Ορυκτά", "continent": "oc", "match": "BHP"},
    "CBA.AX": {"name": "Commonwealth Bank", "sector": "Τράπεζες", "continent": "oc", "match": "Commonwealth Bank"},
    "RIO": {"name": "Rio Tinto", "sector": "Ορυκτά", "continent": "oc", "match": "Rio Tinto"},
    "WES.AX": {"name": "Wesfarmers", "sector": "Λιανεμπόριο", "continent": "oc", "match": "Wesfarmers"},
    "CSL.AX": {"name": "CSL Limited", "sector": "Υγεία", "continent": "oc", "match": "CSL Limited"},
}

CONTINENT_LABELS = {
    "na": {"label": "Βόρεια Αμερική", "flag": "🇺🇸"},
    "eu": {"label": "Ευρώπη", "flag": "🇪🇺"},
    "as": {"label": "Ασία", "flag": "🌏"},
    "oc": {"label": "Ωκεανία", "flag": "🇦🇺"},
}
